### PR TITLE
Create Task/Event

### PR DESCRIPTION
**Pull request by alexfjw**

### CODE REVIEW

**Comment by alexfjw** [comment]
Was thinking of using this for validation instead:

(DATE) to (DATE)
(DATE) for (DURATION)

DATE will be validated by Natty. 
We will only be responsible for getting the above capture groups out & passing it to Natty.

DURATION is a little more tricky, as Natty only handles dates. 
We can still read durations like '4 weeks' as a relative datetime, so we can subtract it from the current datetime and still get a duration out. Am thinking of restricting the inputs here with regex so we can ensure a duration, not datetime is fed here.

**Comment by leeyimin** [comment]
For Deadline and Frequency, if they are not present, do we store null in the respective fields in Task/Event or store null in the values of the Deadline and Frequency objects?

**Comment by alexfjw** [comment]
We store null in Task/Event

**Comment by alexfjw** [comment]
Just rebased this, just take note before working

**Pull request merged**
